apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: 25m
          memory: 25Mi
