apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  securityContext: {}
  volumes:
    - name: tmp
      emptyDir:
        medium: Memory
        sizeLimit: 1k
